name: Build using FAST

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Required for pushing changes
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Download fast-cli
      run: |
        wget -q https://github.com/jewelshkjony/fast-cli/releases/download/v3.2.2/fast.zip
        unzip -q fast.zip
        rm fast.zip
        
    - name: Build with fast-cli
      run: java -jar fast.jar build -dir .
      
    - name: Commit output to repository
      if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-commit build changes [fast-cli]"
        git push
