name: fast build with args

on:
  workflow_dispatch:
    inputs:
      build_args:
        description: 'Additional arguments for fast-cli build'
        required: false
        default: ''
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Download and extract fast-cli
      run: |
        wget -q https://github.com/jewelshkjony/fast-cli/releases/download/v3.2.2/fast.zip
        unzip -q fast.zip -d fast-cli-temp
        rm fast.zip
        
    - name: Running fast build
      run: java -jar fast-cli-temp/fast.jar build -r -dir . ${{ github.event.inputs.build_args }}
        
    - name: Cleanup fast-cli files
      run: rm -rf fast-cli-temp
        
    - name: Commit build results
      if: github.event_name == 'workflow_dispatch'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-commit build changes [fast-cli]"
        git push
