name: fast build tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  fast-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [default, r, s]  # Test variations
    name: FAST Build (${{ matrix.mode }} mode)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set up FAST-CLI
      run: |
        wget -q https://github.com/jewelshkjony/fast-cli/releases/download/v3.2.2/fast.zip
        unzip -q fast.zip -d fast-cli-temp
        rm fast.zip

    - name: fast build (${{ matrix.mode }})
      shell: bash
      run: |
       if [[ "${{ matrix.mode }}" == "r" ]]; then
        java -jar fast-cli-temp/fast.jar sync build -dir . -r
       elif [[ "${{ matrix.mode }}" == "s" ]]; then
        java -jar fast-cli-temp/fast.jar sync build -dir . -s
       else
        java -jar fast-cli-temp/fast.jar sync build -dir .
       fi

    - name: Cleanup FAST-CLI
      run: rm -rf fast-cli-temp
